name: biapy
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - voila
  - itkwidgets
  - jupyterlab
  - nodejs
  - scikit-learn
  - rise
  - jupyter_contrib_nbextensions
  - ipympl
  - ipywidgets
  - pip:
    - napari
    - trackpy
    - tensorflow
    - tqdm
    - torch 
    - torchvision
    - mrc
    - stardist
    - cellpose